version: 1
formatters:
  default:
    format: "%(asctime)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"
handlers:
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/server.log
    when: midnight
    # when: S
    # interval: 60  # 1分钟，以秒为单位
    backupCount: 30
    encoding: utf-8
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: default
root:
  level: INFO
  handlers: [file_handler, console_handler]

